apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: travelo
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/travelo
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
