apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: travelo
type: Opaque
stringData:
  mysql-root-password: root
  mysql-database: travelo
  mysql-user: travelo_user
  mysql-password: travelo_pass
