apiVersion: v1
kind: ServiceAccount
metadata:
  name: travelo-service-account
  namespace: travelo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travelo-role
  namespace: travelo
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travelo-role-binding
  namespace: travelo
subjects:
  - kind: ServiceAccount
    name: travelo-service-account
    namespace: travelo
roleRef:
  kind: Role
  name: travelo-role
  apiGroup: rbac.authorization.k8s.io